name: CI Build, Scan & Push

on:
  schedule:
    - cron: "0 0 1 * *"  # runs monthly on day 1 - 00:00 UTC
  push:
    branches:
      - "**"
    tags:
      - "v*.*"

env:
  IMAGE_NAME: codizz/curl

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Build Container Image (local only)
        uses: docker/build-push-action@v6
        with:
          push: false           # do NOT push before scan
          tags: ${{ steps.meta.outputs.tags }}
          sbom: true

      # Scan image BEFORE pushing
      - name: Run Anchore Security Scan
        id: scan
        uses: anchore/scan-action@v3
        with:
          image: ${{ env.IMAGE_NAME }}:latest
          fail-build: true      # stops job if vulnerabilities found
          output-format: sarif

      # Upload vulnerability report to GitHub Security Dashboard
      - name: Upload SARIF to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      # Push only if scan succeeded
      - name: Push image (only if no vulnerabilities)
        if: success()           # = passed scan
        uses: docker/build-push-action@v6
        with:
          push: true            # now push is allowed
          tags: ${{ steps.meta.outputs.tags }}
          sbom: true
